# Generated by Django 5.0.3 on 2024-05-12 19:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('calories_min', models.FloatField(default=0)),
                ('calories_max', models.FloatField(default=0)),
                ('protein_min', models.FloatField(default=0)),
                ('protein_max', models.FloatField(default=0)),
                ('total_fat_min', models.FloatField(default=0)),
                ('total_fat_max', models.FloatField(default=0)),
                ('saturated_fat_min', models.FloatField(default=0)),
                ('saturated_fat_max', models.FloatField(default=0)),
                ('carbohydrates_min', models.FloatField(default=0)),
                ('carbohydrates_max', models.FloatField(default=0)),
                ('sugar_min', models.FloatField(default=0)),
                ('sugar_max', models.FloatField(default=0)),
                ('fiber_min', models.FloatField(default=0)),
                ('fiber_max', models.FloatField(default=0)),
                ('cholesterol_min', models.FloatField(default=0)),
                ('cholesterol_max', models.FloatField(default=0)),
                ('sodium_grams_min', models.FloatField(default=0)),
                ('sodium_grams_max', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack'), ('other', 'Other'), ('n/a', 'Na')], default='n/a', max_length=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('meal_items', models.ManyToManyField(to='api.food')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
