# Generated by Django 5.0.3 on 2024-05-12 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together={('meal_type', 'date')},
        ),
    ]
