# Generated by Django 5.0.3 on 2024-05-15 22:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_meal_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together={('meal_type', 'date', 'user')},
        ),
    ]
