# Generated by Django 5.0.3 on 2024-05-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_meal_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='time',
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
