# Generated by Django 5.0.3 on 2024-05-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_meal_time_alter_meal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='assumed_total_max_calories',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='assumed_total_max_carbohydrates',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='assumed_total_max_cholesterol',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='assumed_total_max_fiber',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='assumed_total_max_protein',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='assumed_total_max_saturated_fat',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='assumed_total_max_sodium_grams',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='assumed_total_max_sugar',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='assumed_total_max_total_fat',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='assumed_total_min_calories',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='assumed_total_min_carbohydrates',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='assumed_total_min_cholesterol',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='assumed_total_min_fiber',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='assumed_total_min_protein',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='assumed_total_min_saturated_fat',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='assumed_total_min_sodium_grams',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='assumed_total_min_sugar',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='assumed_total_min_total_fat',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
