# Generated by Django 5.0.3 on 2024-05-15 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_meal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
