# Generated by Django 5.0.3 on 2024-05-21 14:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_meal_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meal",
            name="assumed_total_max_calories",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="assumed_total_max_carbohydrates",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="assumed_total_max_cholesterol",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="assumed_total_max_fiber",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="assumed_total_max_protein",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="assumed_total_max_saturated_fat",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="assumed_total_max_sodium_grams",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="assumed_total_max_sugar",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="assumed_total_max_total_fat",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="assumed_total_min_calories",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="assumed_total_min_carbohydrates",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="assumed_total_min_cholesterol",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="assumed_total_min_fiber",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="assumed_total_min_protein",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="assumed_total_min_saturated_fat",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="assumed_total_min_sodium_grams",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="assumed_total_min_sugar",
        ),
        migrations.RemoveField(
            model_name="meal",
            name="assumed_total_min_total_fat",
        ),
    ]
