# Generated by Django 5.0.3 on 2024-05-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_meal_assumed_total_max_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
