# Generated by Django 5.0.3 on 2024-05-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_meal_most_recent_follow_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='initial_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
