# Generated by Django 5.0.3 on 2024-05-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_food_initial_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="caffeine_max",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="food",
            name="caffeine_min",
            field=models.FloatField(default=0),
        ),
    ]
