# Generated by Django 5.0.3 on 2024-05-31 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_food_caffeine_max_food_caffeine_min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='caffeine_max',
        ),
        migrations.RemoveField(
            model_name='food',
            name='caffeine_min',
        ),
    ]
