# Generated by Django 5.0.3 on 2024-06-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_food_caffeine_max_remove_food_caffeine_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
