# Generated by Django 5.0.3 on 2024-06-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_food_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='follow_up',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
